models:
  qwen3.5-9b:
    ttl: 600
    cmd: |
      ./llama-cpp-turboquant/build/bin/llama-server \
      -m ./Huihui-Qwen3.5-9B-abliterated.Q8_0.gguf \
      --port ${PORT} --host 0.0.0.0 \
      -ngl 99 -fa on \
      -ctk turbo3 -ctv turbo3 \
      -c 4096 -t 8 --parallel 1
