models:
  localLLM:
    ttl: 600
    cmd: |
      ./atomic-llama-cpp-turboquant/build/bin/llama-server \
      -m ./gemma-4-e4b-it-Q4_K_M.gguf \
      --port ${PORT} --host 0.0.0.0 \
      -ngl 99 -fa on \
      -ctk q8_0 -ctv q8_0 \
      -c 131072 -t 8 --parallel 4
